sudo: false
language: c
addons:
  apt:
    packages:
      - libpcap-dev
      - libssl-dev
      - libnetfilter-queue-dev
before_script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; fi
script: make
os:
  - linux
  - osx
